# cryptopp has very bad CMakeLists.txt config.
# We have to enforce "cross compiling mode" there by setting CMAKE_SYSTEM_VERSION=NO
# to any "false" value.
hunter_config(cryptopp VERSION ${HUNTER_cryptopp_VERSION} CMAKE_ARGS CMAKE_SYSTEM_VERSION=NO CMAKE_POSITION_INDEPENDENT_CODE=ON)

hunter_config(
    libjson-rpc-cpp
    VERSION ${HUNTER_libjson-rpc-cpp_VERSION}
    CMAKE_ARGS
    UNIX_DOMAIN_SOCKET_SERVER=NO
    UNIX_DOMAIN_SOCKET_CLIENT=NO
    FILE_DESCRIPTOR_SERVER=NO
    FILE_DESCRIPTOR_CLIENT=NO
    TCP_SOCKET_SERVER=NO
    TCP_SOCKET_CLIENT=NO
    HTTP_SERVER=NO
    HTTP_CLIENT=NO
    CMAKE_POSITION_INDEPENDENT_CODE=ON
)

hunter_config(ethash VERSION 0.4.0
    URL https://github.com/chfast/ethash/archive/v0.4.0.tar.gz
    SHA1 fd92ffadff2931877a3b68685dd8c53f0bdec539
    CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CMAKE_CXX_STANDARD=11
)
hunter_config(Boost VERSION 1.65.1 CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CMAKE_CXX_STANDARD=11)
hunter_config(jsoncpp VERSION 1.8.0 CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON)
hunter_config(Snappy VERSION 1.1.6-p0 CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON)

